// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef AboutUI_h
#define AboutUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Return_Button.H>

class AboutUI : public Fl_Double_Window {
  void _AboutUI();
public:
  AboutUI(int X, int Y, int W, int H, const char *L = 0);
  AboutUI(int W, int H, const char *L = 0);
  AboutUI();
private:
  inline void cb_Dismiss_i(Fl_Return_Button*, void*);
  static void cb_Dismiss(Fl_Return_Button*, void*);
public:
  Fl_Box *versionCaption;
};
#endif
