// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef BookmarksUI_h
#define BookmarksUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Fl_Bookmark_Table.h"
extern void cb_BookmarksTable(Fl_Bookmark_Table*, void*);

class BookmarksUI : public Fl_Double_Window {
  void _BookmarksUI();
public:
  BookmarksUI(int X, int Y, int W, int H, const char *L = 0);
  BookmarksUI(int W, int H, const char *L = 0);
  BookmarksUI();
  Fl_Bookmark_Table *bookmarkTable;
};
#endif
