// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef MemDumpUI_h
#define MemDumpUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>
extern void cb_MemDumpClose(Fl_Button*, void*);
#include <FL/Fl_Return_Button.H>
extern void cb_MemDumpGo(Fl_Return_Button*, void*);

class MemDumpUI : public Fl_Double_Window {
  void _MemDumpUI();
public:
  MemDumpUI(int X, int Y, int W, int H, const char *L = 0);
  MemDumpUI(int W, int H, const char *L = 0);
  MemDumpUI();
  Fl_Input *dumpAddress;
  Fl_Input *dumpLength;
  Fl_Check_Button *noAddrCheck;
};
#endif
