// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef MemoryUI_h
#define MemoryUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void cb_MemoryRefresh(Fl_Button*, void*);
#include <FL/Fl_Light_Button.H>
extern void cb_MemoryMode(Fl_Light_Button*, long);
#include "Fl_MemoryView.h"
extern void cb_Memory(Fl_MemoryView*, void*);

class MemoryUI : public Fl_Double_Window {
  void _MemoryUI();
public:
  MemoryUI(int X, int Y, int W, int H, const char *L = 0);
  MemoryUI(int W, int H, const char *L = 0);
  MemoryUI();
  Fl_MemoryView *memory;
};
#endif
