// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef SourceUI_h
#define SourceUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include "Fl_Source_Browser.h"
extern void cb_sourceBrowser(Fl_Source_Browser*, void*);

class SourceUI : public Fl_Double_Window {
  void _SourceUI();
public:
  SourceUI(int X, int Y, int W, int H, const char *L = 0);
  SourceUI(int W, int H, const char *L = 0);
  SourceUI();
  Fl_Choice *sourceFileChoice;
  Fl_Source_Browser *sourceBrowser;
};
#endif
