// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef SymbolsUI_h
#define SymbolsUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Fl_Symbol_Table.h"
extern void cb_SymbolsTable(Fl_Symbol_Table*, void*);

class SymbolsUI : public Fl_Double_Window {
  void _SymbolsUI();
public:
  SymbolsUI(int X, int Y, int W, int H, const char *L = 0);
  SymbolsUI(int W, int H, const char *L = 0);
  SymbolsUI();
  Fl_Symbol_Table *symbolsTable;
};
#endif
